import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { runDoctor, loadInstalledPackageContexts } from "./doctor.js";
import { resolveWikiLink, loadPackageContext } from "./resolver.js";
import type { Graph, PackageContext, ParsedNote } from "./types.js";

export type BuildOptions = {
  entries?: string[];
  depth?: number;
  maxTokens?: number;
  outDir?: string;
  target?: "default" | "cursor" | "claude" | "llms-txt" | "rag";
};

export type BuildFile = {
  packageName: string;
  path: string;
  approxTokens: number;
};

export type BuildResult = {
  files: BuildFile[];
  skipped: BuildFile[];
  graph: Graph;
  outputPath: string;
};

type QueueItem = {
  pkg: PackageContext;
  note: ParsedNote;
  depth: number;
};

export async function buildContext(projectRoot: string, options: BuildOptions = {}): Promise<BuildResult> {
  const doctor = await runDoctor(projectRoot);
  if (!doctor.ok) {
    throw new Error(`Cannot build with doctor errors:\n${doctor.errors.join("\n")}`);
  }

  const currentPackage = await loadPackageContext(projectRoot);
  const installedPackages = await loadInstalledPackageContexts(projectRoot);
  const entries = options.entries?.length ? options.entries : currentPackage.manifest.context.entrypoints;
  const maxDepth = options.depth ?? 3;
  const maxTokens = options.maxTokens ?? 50_000;
  const outDir = options.outDir ?? "dist";

  const included: BuildFile[] = [];
  const skipped: BuildFile[] = [];
  const visited = new Set<string>();
  const queue: QueueItem[] = [];

  for (const entry of entries) {
    const note = currentPackage.notes.get(entry);
    if (!note) {
      throw new Error(`Build entry not found: ${entry}`);
    }
    queue.push({ pkg: currentPackage, note, depth: 0 });
  }

  let usedTokens = 0;
  const sections: string[] = [];

  while (queue.length) {
    const item = queue.shift()!;
    const key = `${item.pkg.name}/${item.note.path}`;
    if (visited.has(key)) {
      continue;
    }
    visited.add(key);

    const approxTokens = estimateTokens(item.note.content);
    const file = {
      packageName: item.pkg.name,
      path: item.note.path,
      approxTokens
    };

    if (usedTokens + approxTokens > maxTokens && included.length > 0) {
      skipped.push(file);
      continue;
    }

    included.push(file);
    usedTokens += approxTokens;
    sections.push(`<!-- source: ${key} -->\n\n${item.note.content.trim()}\n`);

    if (item.depth >= maxDepth) {
      continue;
    }

    for (const link of item.note.wikilinks) {
      const resolved = await resolveWikiLink(link, {
        fromPath: item.note.path,
        currentPackage: item.pkg,
        installedPackages
      });
      if (resolved.status !== "resolved" || !resolved.toPackage || !resolved.toPath) {
        continue;
      }
      const nextPackage = resolved.toPackage === currentPackage.name ? currentPackage : installedPackages.get(resolved.toPackage);
      const nextNote = nextPackage?.notes.get(resolved.toPath);
      if (nextPackage && nextNote) {
        queue.push({ pkg: nextPackage, note: nextNote, depth: item.depth + 1 });
      }
    }
  }

  const outputPath = buildOutputPath(projectRoot, outDir, options.target ?? "default");
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, renderContext(currentPackage.name, included, sections));

  const graphPath = join(projectRoot, outDir, "graph.json");
  const citationsPath = join(projectRoot, outDir, "citations.json");
  await mkdir(dirname(graphPath), { recursive: true });
  await writeFile(graphPath, `${JSON.stringify(doctor.graph, null, 2)}\n`);
  await writeFile(
    citationsPath,
    `${JSON.stringify(
      included.map((file) => ({
        id: `${file.packageName}/${file.path}`,
        packageName: file.packageName,
        path: file.path,
        approxTokens: file.approxTokens
      })),
      null,
      2
    )}\n`
  );

  if (options.target === "rag") {
    await writeFile(join(projectRoot, outDir, "chunks.jsonl"), renderChunks(included, currentPackage, installedPackages));
    await writeFile(
      join(projectRoot, outDir, "embeddings-manifest.json"),
      `${JSON.stringify({ status: "not-generated", chunkCount: included.length }, null, 2)}\n`
    );
  }

  return {
    files: included,
    skipped,
    graph: doctor.graph,
    outputPath
  };
}

function buildOutputPath(projectRoot: string, outDir: string, target: BuildOptions["target"]): string {
  switch (target) {
    case "cursor":
      return join(projectRoot, ".cursor", "rules", "kpm-context.mdc");
    case "claude":
      return join(projectRoot, outDir, "claude-project-context.md");
    case "llms-txt":
      return join(projectRoot, outDir, "llms.txt");
    default:
      return join(projectRoot, outDir, "context.md");
  }
}

function renderContext(projectName: string, files: BuildFile[], sections: string[]): string {
  return [
    `# ${projectName} Context`,
    "",
    `Generated by kpm from ${files.length} Markdown source file${files.length === 1 ? "" : "s"}.`,
    "",
    ...sections
  ].join("\n");
}

function estimateTokens(content: string): number {
  return Math.max(1, Math.ceil(content.length / 4));
}

function renderChunks(
  included: BuildFile[],
  currentPackage: PackageContext,
  installedPackages: Map<string, PackageContext>
): string {
  return included
    .map((file) => {
      const pkg = file.packageName === currentPackage.name ? currentPackage : installedPackages.get(file.packageName);
      const note = pkg?.notes.get(file.path);
      return JSON.stringify({
        id: `${file.packageName}/${file.path}`,
        text: note?.content ?? "",
        source: file.path,
        packageName: file.packageName,
        links: note?.wikilinks.map((link) => link.raw) ?? []
      });
    })
    .join("\n");
}
